modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="bilicrash"
version="1.0.0"
displayName="安装Verity JE就崩溃"
authors="Anonymous"
description='''
A simple mod.
'''

[[dependencies.bilicrash]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bilicrash]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
